train: ../train/images
val: ../valid/images
test: ../test/images

nc: 3
names: ['Hanhnhan', 'Sung', 'Taotau']

roboflow:
  workspace: hcmut-bxzsd
  project: hat_detector-muvnr
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/hcmut-bxzsd/hat_detector-muvnr/dataset/1